### ISSUE TITLE
M3 Section Expansion

### ISSUE THREAD

**Issue by jasparm** [MonashDeepNeuron/HPC-Training#24]
A few things I want to add before we do the section.

- [x] Expand copying files section, need to add different ways to do it and talk about the dedicated url.
- [x] Expand challenges section. I want to have more, smaller challenges and work up to the hard parts a bit slower
- [x] Need to make my own solutions to the challenges to help show what to do
- [x] ~~Add VSCode SSH login to M3~~
- [x] Add vim content

**Comment by jasparm** [comment]
@oraqlle I just read through the instructions for using VSCode on M3, and they don't want people logging into the login node using VSCode coz it puts a bunch of unnecessary load on it. The way they want you to do it is quite involved, to the point where I don't think its worth teaching it. I will put in a link to the M3 docs about it though. tbh I think its better people learn how to navigate linux properly anyway.

**Comment by oraqlle** [comment]
@jasparm where are this docs?

**Comment by jasparm** [comment]
@oraqlle https://docs.massive.org.au/M3/connecting/strudel2/connecting-to-vscode.html

**Comment by oraqlle** [comment]
I see you point @jasparm but this is a more specific setup for something I have never personally used with M3. I can show what Mitch and I were talking about during the workshop this evening, but it's much simpler.

**Comment by jasparm** [comment]
I know what you were talking about, VSCode has a whole thing where it can ssh in and you can access the file system. The issue is that when you do that, it downloads a bunch of crap and runs a vscode server on the login node that you are accessing. That part is the issue coz it takes resources to run. 

They had this note:
Please do not follow the official VS Code documentation for remote servers. If you follow those instructions, you will end up running the VS Code remote server on a login node. The login nodes are a shared resource and we would rather allocate a resource just for you.

**Comment by oraqlle** [comment]
@jasparm
Okay, I hadn't seen that note before. Fair enough. It might be worth then adding content on either vim of emacs to make navigation easier.

**Comment by oraqlle** [comment]
@jasparm do you want to start a new milestone for the M3 chapter so you can track the progress of everything you want to get done a little easier?

**Comment by jasparm** [comment]
Done everything I wanted to in this issue
