### ISSUE TITLE
User Input in C

### ISSUE THREAD

**Issue by oraqlle** [MonashDeepNeuron/HPC-Training#29]
Add a section to the C chapter detailing how to take user input from the terminal using `scanf()`.

**Comment by Abhishekm0410** [comment]
Please assign this to me , I would like to work on it.

**Comment by oraqlle** [comment]
Done @Abhishekm0410, let myself or @Ozzywap know if you need any guidance.

**Comment by Abhishekm0410** [comment]
Can I directly send a pull request after completing the project?

**Comment by oraqlle** [comment]
Yes

**Comment by Abhishekm0410** [comment]
I am not able to compile mdbook on my system . Is there any other way possible?

**Comment by jasparm** [comment]
@Abhishekm0410 What is the exact issue you are running into?

**Comment by Abhishekm0410** [comment]
According to the contributing guideline I was setting up mdbook on my system using rust compiler but there is a compilation error in doing so. I have pasted the exact error for you to see. 


error: could not compile `winapi` (build script) due to previous error
error: failed to compile `mdbook v0.4.31`, intermediate artifacts can be found at `C:\Users\Dell\AppData\Local\Temp\cargo-installq4A96I`

**Comment by jasparm** [comment]
Can you please post full error log. Rust is usually very good at telling you what's wrong, so the log is important.

**Comment by jasparm** [comment]
Oh uh that should be easy fix u don't have a linker installed or cargo can't find it for some reason. Just make sure the gcc tool chain is fully installed then try again.

**Comment by oraqlle** [comment]
@Abhishekm0410 how did you install Rust? You can try reinstalling Rust.

Otherwise, my best guess is that the crate `winapi`; which is just a Rust wrapper around the actual Windows API which is written in C and C++, cannot be built by Cargo directly and needs to be built using a C++ build system. On Windows this is Visual Studio and the MSVC toolchain. In the error says to ensure that the C++ build tools workload is installed.

> ```sh
> note: in the Visual Studio installer, ensure the "C++ build tools" workload is selected
> ```

**Comment by oraqlle** [comment]
Are you getting an error, if so can you paste the error message (in code blocks). If its "working" but not doing what's expected elaborate on what you want it to be doing, what it appears to be doing and what you have tried to fix it.

**Comment by Abhishekm0410** [comment]
1)Firstly I am not able to change my branch from main branch to the one I created.

$ git checkout git-checkout--b<add_info>-dev
bash: add_info: No such file or directory

2)I have cloned the repository and added the file using Visual Studio , how to see the changes I made are in place .
3)Also how should I send the pull request for it ?
4) I read about the mdbook serve --open command in the contributing module but I don't know what my next step should be as it is not showing any errors rather shows this
$ mdbook serve --open
2023-07-15 16:43:15 [INFO] (mdbook::book): Book building has started
2023-07-15 16:43:15 [INFO] (mdbook::book): Running the html backend
2023-07-15 16:43:15 [INFO] (mdbook::cmd::serve): Serving on: http://localhost:3000
2023-07-15 16:43:15 [INFO] (mdbook): Opening web browser
2023-07-15 16:43:15 [INFO] (warp::server): Server::run; addr=[::1]:3000
2023-07-15 16:43:15 [INFO] (warp::server): listening on http://[::1]:3000
2023-07-15 16:43:15 [INFO] (mdbook::cmd::watch): Listening for changes...

**Comment by oraqlle** [comment]
1. To change branch `git checkout <branch-name>`, to create a branch and change to it `git checkout -b <new-branch>`
2. To preview the changes you need to serve it locally (see 4.)
3. Yes you should create a PR once you are done with your changes and request us to review it but it looks like you didn't clone the repo but you forked it. You don't actually have to do this. You can clone the repo, create a new branch and checkout to it, make you changes, push the commits on the new local branch to the remote (here). Create a PR from your branch with the changes to `dev`. We will review it and put it in the pipeline to be released on main shortly after.
4. The `mdbook serve --open` command is working as expected. it tells you some meta details about how it is running which can be used for debugging however, to preview the book in the browser simply copy the localhost address it gives you. It will say something like `Serving on: http//localhost:3000`. This is a local server so you can copy the address into your browser and preview the book. As you write and save the changed/new files the book will rebuild and it will be reflected in the browser.

To help you out, I've created a branch attached to this issue on the remote. Running the following commands will get you in the right spot.

```sh
git clone https://github.com/MonashDeepNeuron/HPC-Training.git
cd HPC-Training
git fetch origin
git checkout 29-user-input-in-c
mdbook serve --open
```

**Comment by Abhishekm0410** [comment]
I am trying to send a pull request without  forking as you have suggested above but I am facing this error
 
Remote: Permission to MonashDeepNeuron/HPC-Training.git denied to Abhishekm0410.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/MonashDeepNeuron/HPC-Training.git/': The requested URL returned error: 403

**Comment by oraqlle** [comment]
I fixed the repo permissions, should be able to push as long as you have your credentials setup for Git.

**Comment by Abhishekm0410** [comment]
@oraqlle I am facing the same issue now also . Is there any way I can push the changes I made?

Remote: Permission to MonashDeepNeuron/HPC-Training.git denied to Abhishekm0410.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/MonashDeepNeuron/HPC-Training.git/': The requested URL returned error: 403

**Comment by oraqlle** [comment]
You might not have you GitHub authentication setup with Git. Is it asking you to enter an username and password. 

The other alternative is the command you are running is not correct. What exactly are you running?

**Comment by Abhishekm0410** [comment]
I am using push command of visual studio to the branch 29-user-input-in-c

**Comment by oraqlle** [comment]
Have you signed in to GitHub on Visual Studio?

**Comment by Abhishekm0410** [comment]
Hi. I pushed it through GitHub CLI. The issue seems to be on the access authentication part. I believe I do not have push access on  the main repo. The exact error: remote: Permission to MonashDeepNeuron/HPC-Training.git denied to Abhishekm0410.

**Comment by oraqlle** [comment]
Okay, just realized you were never invited to the org, this should be fixed now.

**Comment by Abhishekm0410** [comment]
I have submitted a pull request for the given project. No I am student from India pursuing bachelors in Computer Science. Can I be a member of Monash DeepNeuron?

**Comment by oraqlle** [comment]
Unfortunately we are a student team based in Melbourne Australia which is only open to students of Monash University. However, we welcome external contributors and their contributions. I'll review the pull request.
