### ISSUE TITLE
M3 Content

### ISSUE THREAD

**Issue by oraqlle** [MonashDeepNeuron/HPC-Training#5]
- [x] Logging In
  - [x] SSH or PuTTY
- [x] Software and Tooling
- [x] Linux commands
- [x] Bash scripts
- [x] SLURM
- [x] Shared Filesystem
- [x] Challenges

**Comment by jasparm** [comment]
Changed compiling section to Software and Tooling, to broaden topic, allowing me to talk about M3 modules in general, as well as specific uses for them.
